"""add missing hashed password column

Revision ID: fd70c0fe2fb1
Revises: 6b5026d4a898
Create Date: 2026-06-30 17:56:25.319373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd70c0fe2fb1'
down_revision: Union[str, Sequence[str], None] = '6b5026d4a898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_coaching_centres_id'), table_name='coaching_centres')
    op.drop_index(op.f('ix_coaching_centres_name'), table_name='coaching_centres')
    op.drop_index(op.f('ix_coaching_centres_rating'), table_name='coaching_centres')
    op.drop_index(op.f('ix_coaching_centres_subject'), table_name='coaching_centres')
    op.drop_table('coaching_centres')
    op.add_column('asher_developer', sa.Column('hashed_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asher_developer', 'hashed_password')
    op.create_table('coaching_centres',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('coaching_centres_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('coaching_centres_pkey'))
    )
    op.create_index(op.f('ix_coaching_centres_subject'), 'coaching_centres', ['subject'], unique=False)
    op.create_index(op.f('ix_coaching_centres_rating'), 'coaching_centres', ['rating'], unique=False)
    op.create_index(op.f('ix_coaching_centres_name'), 'coaching_centres', ['name'], unique=False)
    op.create_index(op.f('ix_coaching_centres_id'), 'coaching_centres', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###
